
---
title: "DA2 Resampling Homework"
output: pdf_document
---

Name: ________________________
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Data
Using the Default data from ISLR


```{r, message=F, warning=F, fig.width=4, fig.height=3, fig.align="center"}
library(tidyverse)
library(ISLR)
dfDefault <- Default
tst <- subset(dfDefault, default == 'No')
dfDefault <- Default
ggplot(dfDefault, aes(balance, fill = default)) +
  geom_histogram(binwidth = 500)

```


###  Deliverables: Model Cross Validation

Using the Ranger package, cross validate - hold out 10% for testing. 

```{r, message=F, warning=F, fig.width=4, fig.height=3, fig.align="center"}
library(tidyverse)
library(ISLR)
library(caret)
library(MLmetrics)
library(klaR)
library(naivebayes)
library(matrixcalc)
library(car)
library(mlbench)
library(ranger)
library(randomForest)

dfDefault <- Default
testSplit <- .1
totalSampleSize <- nrow(dfDefault)
testSampleSize <- round(totalSampleSize*testSplit)
trainSampleSize <- totalSampleSize - testSampleSize
tindexes <- sample(1:nrow(dfDefault), testSampleSize)
indexes <- sample(1:nrow(dfDefault[-tindexes,]), trainSampleSize)
xTrain <- dfDefault[indexes, ]
xTest <- dfDefault[tindexes,]

# 2 minutes
train_control <- trainControl(method = 'cv', number = 10)
caretNBModel <- train(default ~ student + balance + income,  data = xTrain, method = 'ranger')
xTest$cvPred <- predict(caretNBModel, xTest[,-1], prob = TRUE)
confusionMatrix(xTest$cvPred, xTest$default)

```


###  Model Selection and Parameter estimation

Now compare the Random Forest with naive_bayes, svmRadial and rf. Map results to a grid and show:


```{r, message=F, warning=F, fig.width=4, fig.height=3, fig.align="center"}

results <- matrix(ncol = 2, nrow=4)
results[1,1] <- 'naive_bayes'
results[2,1] <- 'ranger'
results[3,1] <- 'svmRadial'
results[4,1] <- 'rf'
results


# here we're running the models through with default parameters - just to compare models
# 4 minutes

for(i in 1:nrow(results) )
{
  caretMod <- train(default ~ student + balance + income,  data = xTrain, method = results[i,1])
  xTest$cvPred <- predict(caretMod, xTest[,-1])
  tst <- confusionMatrix(xTest$cvPred, xTest$default)
  # TPR - True Positive Rate
  results[i,2] <- tst$table[2,2]/(tst$table[2,2] + tst$table[2,1])
}
results
tst # this is looking good!

```



```{r, message=F, warning=F, eval=F, echo=T}
```

```{r, message=F, warning=F, eval=F, echo=T}
```

